name: Artifacts Helper Keyring Releases

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/artifacts-helper/codespaces_artifacts_helper_keyring

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: wntrblm/nox@57f9e10c4eef84277dcd692d0056420c947674f9 # 2026.08.10
        with:
          python-versions: "3.11, 3.12"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4.4
        with:
          version: "2.15.1"
          python-version-file: "src/artifacts-helper/codespaces_artifacts_helper_keyring/pyproject.toml"

      - name: Run nox release
        run: pdm release

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: codespaces_artifacts_helper_keyring
          path: |
            src/artifacts-helper/codespaces_artifacts_helper_keyring/dist
